### PR TITLE
able to return products in a cart

### PR DESCRIPTION
**Pull request by glenvollmer**
route to place an order POST /orders/new 

{
  "buyer_id": ,
  "paymentType_id": ,
  "product_id": 
}

route to add another item to cart PUT /orders/update/:id

{
  "buyer_id": ,
  "paymentType_id": ,
  "product_id": 
}

route to get a single order GET /orders/:id

### CODE REVIEW

**Comment by Staffmaster00** [comment]
It does not create an order date in orders when you make the order for orderProducts.

When I get the individual orders it returns the cart but the buyer_id and payment types are null and undefined respectively. This is after running a put though.

**Comment by glenvollmer** [comment]
want to me merge it and then we can fix that? or do you want me to fix it then merge it

**Comment by Staffmaster00** [comment]
Depends, does anyone need this specific code for anything they want try this weekend? If so I'd say merge it so they have it otherwise no. 

In any case I think people can use the code via copy paste or fetching the branch to work on it.

**Comment by Staffmaster00** [comment]
I think Joe says we have to keep production code on the master but I think this TECHNICALLY meets the requirements.

**Pull request merged**
